title: "AgIR Documentation"
description: "Agricultural Image Repository & CV Toolkit"
theme: jekyll-theme-cayman  # or minimal, slate

# Navigation structure
navigation:
  - title: "Dataset Overview"
    url: /datasets/overview
  - title: "Examples"
    url: /examples/images
  - title: "Technical Docs"
    url: /GETTING_STARTED/installation
