name: agcv
channels:
  - conda-forge
  - nvidia   # for pytorch-cuda builds
  - defaults
dependencies:
  # Core
  - python=3.13
  - pip

  # For testing / dev
  - pytest
  - black
  - ruff
  - mypy

  # Scientific / CV stack (Conda will grab system libs cleanly)
  - numpy
  - pillow
  - opencv

  # Visualization
  - matplotlib

  # Use pip for packages not always in Conda
  - pip:
      - hydra-core>=1.3
      - typer>=0.12
      - pydantic>=2.6
      - rich>=13
      - cvat-sdk>=2.14
      - pyarrow>=21.0
      - fastparquet>=2024.11.0
      # Torch stack (CPU-only by default, add cudatoolkit if GPU available)
      - torch
      - torchvision
      # Segmentation-specific
      - segmentation-models-pytorch>=0.3.3
      - pytorch-lightning>=2.0.0
      # GPU selection
      - gputil>=1.4.0
