name: agcv
channels:
  - conda-forge
  - nvidia      # for pytorch-cuda builds
  - defaults

dependencies:
  # === Core ===
  - python=3.13
  - pip

  # === Development / Testing ===
  - pytest
  - black
  - ruff
  - mypy

  # === Scientific / Computer Vision Stack ===
  - numpy
  - pillow
  - opencv
  - matplotlib

  # === Pip-installed Packages ===
  - pip:
      # ---- Configuration / CLI ----
      - hydra-core>=1.3
      - typer>=0.12
      - pydantic>=2.6
      - rich>=13

      # ---- Data Handling ----
      - pyarrow>=21.0.0
      - fastparquet>=2024.11.0

      # ---- CV / ML Core ----
      - torch>=2.8.0
      - torchmetrics==1.8.2
      - torchvision==0.23.0
      - albumentationsx>=2.0.12

      # ---- Segmentation / Deep Learning ----
      - segmentation-models-pytorch>=0.5.0
      - pytorch-lightning>=2.5.5

      # ---- Tools / SDKs ----
      - cvat-sdk>=2.14
      - GPUtil>=1.4.0
