# conf/preprocess/default.yaml
# Preprocessing configuration for training data preparation

# Source of data to preprocess
source:
  type: "cvat_download"  # "cvat_download" | "custom" | "inference_results"
  
  # Database for image resolution (when images not in CVAT download)
  db: "semif"  # "semif" | "field" | null
  
  # Task selection for cvat_download type:
  # - null (default): combine ALL tasks in cvat_downloads folder
  # - ["task1", "task2"]: only combine specified tasks (by sanitized directory name)
  tasks:  # null = all tasks, or list of task names

  
  # For custom type: specify custom paths
  custom_images_dir: null
  custom_masks_dir: null

# Image resolution (NEW STEP)
# Resolves image locations when downloading masks-only from CVAT
resolve_images:
  enabled: true  # Set to false to skip image resolution
  
  # Search locations in order:
  # 1. run_root/images (from prior inference)
  # 2. cvat_downloads/<task>/images
  # 3. Database query + copy to resolved_images

# Preprocessing steps
pad_gridcrop_resize:
  enabled: true
  
  # Concurrency settings
  use_concurrency: true
  num_workers: 16
  
  # Target size for all images/masks
  size:
    height: 2048
    width: 2048
  
  # If true, skip saving images/masks with no annotations
  ignore_empty_data: true
  
  # If true, remove source files after processing (saves disk space)
  remove_src: false
  
  # Padding settings for images smaller than target
  pad:
    enabled: true
    mode: constant  # constant | reflect | replicate
    fill: 0  # Fill value for padding (0 = black)
  
  # Grid cropping for very large images
  grid_crop:
    enabled: true
    stride: 512  # Overlap between tiles
    threshold: 2.5  # Crop if image is this many times larger than target
  
  # Resize settings for images between target and threshold
  resize:
    enabled: true
    interpolation:
      image: BILINEAR  # NEAREST | BILINEAR | BICUBIC | LANCZOS
      mask: NEAREST    # Always use NEAREST for masks

# Train/val/test split
split:
  enabled: true
  
  # Concurrency settings
  use_concurrency: true
  num_workers: 16
  
  # Split ratios (must sum to ~1.0)
  train: 0.8
  val: 0.15
  test: 0.05
  
  # If true, remove preprocessed files after splitting (saves disk space)
  remove_src: false
  
  # Random seed for reproducible splits (inherits from train.seed if not set)
  seed: null

# Compute dataset statistics for normalization
compute_data_stats:
  enabled: true
  
  # Concurrency settings
  use_concurrency: true
  num_workers: 16