# _config.yml
title: AgIR Dataset
description: Agricultural Image Repository

# Use gem-based theme (NOT remote_theme for local dev)
theme: just-the-docs

# Basic settings
baseurl: ""
url: ""

# Enable search
search_enabled: true

# Color scheme
color_scheme: light

# Plugins
plugins:
  - jekyll-seo-tag