# _config.yml
title: AgIR Dataset
description: Agricultural Image Repository

# Theme
remote_theme: just-the-docs

# Basic settings
baseurl: ""
url: ""

# Enable search
search_enabled: true
search:
  heading_level: 2
  previews: 3

# Color scheme
color_scheme: light

# Callouts
callouts:
  note:
    title: Note
    color: blue
  tip:
    title: Pro Tip
    color: green
  warning:
    title: Warning
    color: yellow
  important:
    title: Important
    color: red

# Plugins
plugins:
  - jekyll-seo-tag

# Aux links (top right corner)
aux_links:
  "GitHub Repository":
    - "//github.com/mkutu/AgIR-CVToolkit"
  
# Footer
footer_content: "Copyright &copy; 2025 AgIR Dataset. <a href='https://github.com/mkutu/AgIR-CVToolkit'>View on GitHub</a>"